### ISSUE TITLE
Function "include" is not allowed while creating invoice

### ISSUE THREAD

**Issue by matze19999** [kimai/DemoBundle#11] opened 2024-12-22 20:33 UTC
I've installed the 2.7 Demo Bundle and selected the demo template for invoice, but after clicking on preview, I get this error message:

![image](https://github.com/user-attachments/assets/400e852c-e1fc-4e34-8edb-1e99ff749982)
![image](https://github.com/user-attachments/assets/986e11d1-c898-4713-b607-c536939f9c30)
![image](https://github.com/user-attachments/assets/226d2be3-f89d-4344-9245-00600c21dbb7)

**Comment by matze19999** [comment] 2024-12-22 20:48
This only happens while using the dev docker container. It works for the apache tag

**Comment by kevinpapst** [comment] 2024-12-22 21:40
Yep, that's caused by some change in one of the latest Twig updates, causing issues in dev environments and for HTML template. I have stumbled upon that as well and it will be fixed with the next release.

Has nothing to do with the Demo bundle. Closing here.

**Closed as completed by kevinpapst** 2024-12-22 21:40 UTC
